version: '2'
services:
        app:
                image: 'admios-movies-management:latest'
                build:
                        context: .
                ports:
                        - "5000:5000"
                container_name: app
                depends_on:
                        - postgresqldb
                environment:
                        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/moviesmanagement
                        - SPRING_DATASOURCE_USERNAME=postgres
                        - SPRING_DATASOURCE_PASSWORD=postgres
                        - SPRING_JPA_HIBERNATE_DDL_AUTO=create
        postgresqldb:
                image: postgres
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_DB=moviesmanagement